# Generated by Django 6.0.1 on 2026-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
